### ISSUE TITLE
Search results not rendering any results

### ISSUE THREAD

**Issue by saikarthikp9** [hauxir/rapidbay#19]
I am trying to use the docker-compose file given for VPS, but I am using a local server. See Docker-compose file below.

My modifications:
I have avoided the usage of Caddy as I do not want to use it outside my local network. I believe this is the only use for Caddy here.
I was able to retrieve the Jackett API key and paste it as env var for rapidbay.
I am using a custom docker image for arm using this image as base: hauxir/libtorrent-python3-ubuntu-arm64v8:latest. Docker Build was smooth and successful without any other modifications.

Logs of RapidBay:
```
* Serving Flask app 'app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://172.22.0.2:5000/ (Press CTRL+C to quit)
```

docker-compose:
```
version: "2"
services:
  nordvpn:
    cap_add:
    - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - USER=email
      - PASS=password
      - COUNTRY="United States"
    image: "azinchen/nordvpn"
    container_name: nordvpn
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    volumes:
      - jackett_config:/config
    container_name: jackett
    ports:
      - 9117:9117
    restart: unless-stopped

  rapidbay:
    network_mode: "service:nordvpn"
    image: "dockerrepo/rapidbay-arm-0.0.1:latest"
    environment:
      - PASSWORD=123456
      - JACKETT_HOST=10.0.1.30
      - JACKETT_API_KEY=PLACEHOLDER_CHANGE_THIS_LATER
    container_name: rapidbay
    restart: unless-stopped

volumes: 
  jackett_config:
    driver: local  
```

What URL should I visit to access rapidbay?
I understand all traffic is going through the nordvpn container (network_mode: "service:nordvpn"). So no ports are exposed for the rapidbay container itself but in Dockerfile I see EXPOSE 5000. 

Please advice. I am also trying to understand the networking aspects here. Thanks!
If this is successful, I can create a PR for the arm build as well if you want.

**Comment by saikarthikp9** [comment]
Reporting additional tests and results below. Please find docker-compose file below as well.

Tested new VPN image: https://github.com/qdm12/gluetun
Manually tested jackett search from jackett UI and it is showing search results. 

**Now I am able to access rapidbay! However, when I search, I see 200 response in rapidbay logs but I don't see any search results on rapidbay UI.** 

Please help. 

docker-compose:
```
version: "2"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPNSP=nordvpn
      - OPENVPN_USER=email
      - OPENVPN_PASSWORD= password
      - REGION=United States
    ports:
      - 5000:5000 #rapidbay
    restart: unless-stopped

  jackett:
    ports:
      - 9117:9117
    image: linuxserver/jackett
    volumes:
      - jackett_config:/config
    container_name: jackett
    restart: unless-stopped

  rapidbay:
    network_mode: "service:gluetun"
    image: "dockerrepo/rapidbay-arm-0.0.1:latest"
    environment:
      - PASSWORD=password
      - JACKETT_HOST=http://10.0.1.30:9117
      - JACKETT_API_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxx
      - SUBTITLE_LANGUAGES="['en']"
    container_name: rapidbay
    restart: unless-stopped

volumes: 
  jackett_config:
    driver: local    
```
